In [22]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

file_path = 'test.csv'
df = pd.read_csv(file_path)

print("Первые 5 строк датасета:")
df.head()

Первые 5 строк датасета:

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [23]:
missing_values = df.isnull().sum()

print("Количество пропущенных значений в каждом столбце:")
print(missing_values)

Количество пропущенных значений в каждом столбце:
PassengerId       0
HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
Name             94
dtype: int64

In [35]:
fill_values = {
    'Age': df['Age'].mean(),
    'HomePlanet': df['HomePlanet'].mode()[0] if 'HomePlanet' in df else None,
    'CryoSleep': df['CryoSleep'].mode()[0] if 'CryoSleep' in df else None,
    'Destination': df['Destination'].mode()[0] if 'Destination' in df else None,
    'VIP': df['VIP'].mode()[0] if 'VIP' in df else None,
    'RoomService': df['RoomService'].mean() if 'RoomService' in df else None,
    'FoodCourt': df['FoodCourt'].mean() if 'FoodCourt' in df else None,
    'ShoppingMall': df['ShoppingMall'].mean() if 'ShoppingMall' in df else None,
    'Spa': df['Spa'].mean() if 'Spa' in df else None,
    'VRDeck': df['VRDeck'].mean() if 'VRDeck' in df else None,
    'Name': df['Name'].mode()[0] if 'Name' in df else None,
    'Cabin': df['Cabin'].mode()[0] if 'Cabin' in df else None
}

# убираем None, чтобы не было ошибок
fill_values = {k: v for k, v in fill_values.items() if v is not None}

df.fillna(fill_values, inplace=True)

In [36]:
nan_matrix = df.isnull()
nan_matrix.sum()

PassengerId                  0
Cabin                        0
Age                          0
RoomService                  0
FoodCourt                    0
ShoppingMall                 0
Spa                          0
VRDeck                       0
Name                         0
Destination_PSO J318.5-22    0
Destination_TRAPPIST-1e      0
HomePlanet_Europa            0
HomePlanet_Mars              0
CryoSleep_True               0
VIP_True                     0
dtype: int64

In [37]:
scaler = MinMaxScaler()

scaler.fit(df[['Age']])
df['Age'] = scaler.transform(df[['Age']])

scaler.fit(df[['RoomService']])
df['RoomService'] = scaler.transform(df[['RoomService']])

scaler.fit(df[['FoodCourt']])
df['FoodCourt'] = scaler.transform(df[['FoodCourt']])

scaler.fit(df[['ShoppingMall']])
df['ShoppingMall'] = scaler.transform(df[['ShoppingMall']])

scaler.fit(df[['Spa']])
df['Spa'] = scaler.transform(df[['Spa']])

scaler.fit(df[['VRDeck']])
df['VRDeck'] = scaler.transform(df[['VRDeck']])

In [28]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,0.341772,False,0.000000,0.000000,0.00000,0.000000,0.000000,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,0.240506,False,0.000000,0.000356,0.00000,0.142260,0.000000,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,0.392405,False,0.000000,0.000000,0.00000,0.000000,0.000000,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,0.481013,False,0.000000,0.263206,0.00000,0.009121,0.026266,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,0.253165,False,0.000865,0.000000,0.07658,0.000000,0.000000,Brence Harperez

In [38]:

le = LabelEncoder()

df = pd.get_dummies(df, columns=['Destination'], drop_first=True)

df = pd.get_dummies(df, columns=['HomePlanet'], drop_first=True)

df = pd.get_dummies(df, columns=['CryoSleep'], drop_first=True)

df = pd.get_dummies(df, columns=['VIP'], drop_first=True)

df['Name'] = le.fit_transform(df['Name'])

df['Cabin'] = le.fit_transform(df['Cabin'])

KeyError: "None of [Index(['Destination'], dtype='object')] are in the [columns]"

In [39]:
df.head()

,PassengerId,Cabin,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_True,VIP_True
0,0013_01,2784,0.341772,0.000000,0.000000,0.00000,0.000000,0.000000,2912,False,True,False,False,True,False
1,0018_01,1867,0.240506,0.000000,0.000356,0.00000,0.142260,0.000000,2406,False,True,False,False,False,False
2,0019_01,257,0.392405,0.000000,0.000000,0.00000,0.000000,0.000000,3376,False,False,True,False,True,False
3,0021_01,259,0.481013,0.000000,0.263206,0.00000,0.009121,0.026266,2711,False,True,True,False,False,False
4,0023_01,1940,0.253165,0.000865,0.000000,0.07658,0.000000,0.000000,668,False,True,False,False,False,False

In [40]:
df.to_csv("processed_titanic.csv", index=False)